/*
 * Copyright 2026 Martin Absmeier.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.am.albion.tradecalc.config;

import lombok.Getter;
import lombok.Setter;
import org.springframework.boot.context.properties.ConfigurationProperties;

import java.util.List;

/**
 * Configuration properties for the <strong>Albion Online Data API</strong> client.
 *
 * <p>Bound to the {@code albion.api.*} prefix in {@code application.yml}. These values
 * describe <em>which</em> market data trade-calc consumes — the
 * <em>how</em> (caching, refresh interval) is configured separately via
 * {@link CacheProperties}.</p>
 *
 * <p>Typical configuration block:
 * <pre>{@code
 * albion:
 *   api:
 *     base-url: https://west.albion-online-data.com
 *     server: europe
 *     locations: [Lymhurst, Fort Sterling, Martlock, Bridgewatch, Thetford]
 *     qualities: [1]
 * }</pre>
 *
 * <p>Getters and setters are generated by Lombok at compile time.</p>
 *
 * @author Martin Absmeier
 * @since 1.0.0
 * @see CacheProperties
 */
@Getter
@Setter
@ConfigurationProperties(prefix = "albion.api")
public class AlbionApiProperties {

    private String baseUrl;
    private String server;
    private List<String> locations;
    private List<Integer> qualities;
}