/*
 * Copyright 2026 Martin Absmeier.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.am.albion.tradecalc.config;

import lombok.Getter;
import lombok.Setter;
import org.springframework.boot.context.properties.ConfigurationProperties;

import java.time.Duration;

/**
 * Configuration properties for the Caffeine-backed <strong>market price cache</strong>.
 *
 * <p>Bound to the {@code cache.market.*} prefix in {@code application.yml}. These values
 * control how often live market data is refreshed, how long cache entries stay valid,
 * and how many items can be held in memory.</p>
 *
 * <p>Typical configuration block:
 * <pre>{@code
 * cache:
 *   market:
 *     refresh-interval: PT5M    # background refresh every 5 minutes
 *     ttl: PT15M                # cache entries expire after 15 minutes
 *     max-items: 5000           # maximum number of cached items
 * }</pre>
 *
 * <p>Duration values follow the ISO-8601 format (e.g. {@code PT5M} = 5 minutes,
 * {@code PT1H30M} = 1 hour 30 minutes) which Spring Boot parses automatically.</p>
 *
 * <p>Getters and setters are generated by Lombok at compile time.</p>
 *
 * @author Martin Absmeier
 * @since 1.0.0
 */
@Getter
@Setter
@ConfigurationProperties(prefix = "cache.market")
public class CacheProperties {

    private Duration refreshInterval = Duration.ofMinutes(5);
    private Duration ttl = Duration.ofMinutes(15);
    private int maxItems = 5000;
}